APIANTICHEATcs = {}
--//Auth System\\-- 
APIANTICHEATcs.License = "API_AC_ChampionRP_zFAILJnLtA0zsxcdKbxzwyIR" -- here u put your key
--//Permission System\\-- 
APIANTICHEATcs.Spectate = {"apisupporter","apimod","apiadmin","apiprojektleiter"} --DO NOT TOUCH IF YOU DON'T KNOW WHAT ARE U DOING 
APIANTICHEATcs.Bypass = {"apisupporter","apimod","apiadmin","apiprojektleiter"} --For example. Delete apimod if u dont want mods to have bypass
APIANTICHEATcs.Commands = {"apisupporter","apimod","apiadmin","apiprojektleiter"} --For example. Delete apimod if u dont want mods to have access to api commands
--//Anticheat Version\\-- 
APIANTICHEATcs.Version = "API8.5a" --DONT TOUCH THIS
--//Webhook for bans\\--
APIANTICHEATcs.Webhooklink = "https://discord.com/api/webhooks/874269136665059338/IlXyBkpfVpl1AtaXpUlbt4bUJ_fAtpE48SVs6M5fcHUjXiJ4mPCXyP2ueFt45LUPA89z" -- General injections logs -- Required.
APIANTICHEATcs.logswebhook = "https://discord.com/api/webhooks/874269203119607809/CPF9uqQ3_0drteHJ3dNwDxdQjWx3r6OU6JfkLid4RQq3wlyvYAzgzm9a3efm1n-pB_gc" -- Global logs
APIANTICHEATcs.explosionswebhook = "https://discord.com/api/webhooks/874269246618738688/IRckIlYDXyaxgfuhSlTnRSjzvJGGogpVo_r5PLcdk0cSBSmh20w7Z5kLPXxqfyHHlP68" -- explosion logs
APIANTICHEATcs.ScreenshotWebhook = "https://discord.com/api/webhooks/874269314113478727/kH2zyx0XqqjSw2ZbqS29aLEjUctykwSy9oNPY_M3bfyMgtyAKYYJayWAOTyGjgrBQHhA" -- Screenshot will be sended on this webhook
APIANTICHEATcs.ConnectionLogs = true -- disable if u dont want connection logs (SWITCHER) NEW!
APIANTICHEATcs.WebhookConnect = "https://discord.com/api/webhooks/874269311357812766/tICu28Ihh2WBVgZqTabVEkfd0nOzczRHxZw7LEpWnbmi2dN4pXxn5iU_woMmyy_LhMB_" -- player connecting log
APIANTICHEATcs.PublicDiscordLog = true -- disable if u dont want Public logs (SWITCHER)
APIANTICHEATcs.PublicBansWebhook = "https://discord.com/api/webhooks/874269240872534067/JgcKOk5cGnRN1okAACHiQV_WVDvK6uiccXTpuj8hPRro3QX7pYjcBjq0PyEwyN3_7Onm"
--//Connecting system\\--
APIANTICHEATcs.ForceDiscord = false -- This will force the users to have discord linked to fivem (Most of the cheaters will not use Discord on FiveM)
APIANTICHEATcs.ForceDiscordMessage = "Öffne dein Discord und habe es offen!" -- Force Discord Kick Message (If the player doesn't have Discord Linked, will get kicked with that message)
APIANTICHEATcs.ForceSteam = true -- This will force the users to have steam linked to fivem
APIANTICHEATcs.ForceSteamMessage = "Öffne dein Steam und habe es offen!" -- Force Steam Kick Message (If the player doesn't have Discord Linked, will get kicked with that message)
--//Message Ban\\--
APIANTICHEATcs.BanMessage = "You have been *globaly* banned from FiveM for cheating. This ban will expire in ~249.5 days. Please do note that the FiveM staff can _not_ assist with this ban. Your ban ID is 5989e5db-7c89-4764-812d-9f8db400aacd." --here u can change ban meesage
--//VPN CHECKER\\--
APIANTICHEATcs.AntiVPN = true
--//antimass particles\\--
APIANTICHEATcs.AntiMassParticles = true -- new! 
--//Anti ClearPedTask\\--
APIANTICHEATcs.ClearPedTasksImmediatelyLog = true --Automatically detect ClearPedTasksImmediately (detect cheaters that are kicking out of vehicles other players) NEW! (it send log)
APIANTICHEATcs.ClearPedTasksImmediatelyBan = true --Automatically detect ClearPedTasksImmediately (detect cheaters that are kicking out of vehicles other players) NEW! Instant ban!

APIANTICHEATcs.ClearPedsVehsPropsAfterDetection = true
--//ANTI CLIENT STOP\\--
APIANTICHEATcs.AntiClientStop = true -- Automatically detect if someone stop client anticheat (HEARTBEAT'S) | NEW!
--//Events System\\--
APIANTICHEATcs.EventsRateLimit = true
APIANTICHEATcs.RateLimitTimer = 3000 -- RateLimit Count is deleting every x MS x = APIANTICHEATcs.RateLimitTimer DEFAULT AND RECOMMEND: 3000 its 3 secounds
APIANTICHEATcs.RateLimitedEvents = { -- limit that means someone can use trigger limit times example 3, in RateLimitTimer example. 3000 ms (3 secounds), so if someone trigger 4 times in 3 secounds he will be banned!
  ["esx_illegal_drugs:startHarvestWeed"] = {limit = 3},
  ["esx_drugs:pickedUpCannabis"] = {limit = 3},
  ["esx_drugs:startHarvestWeed"] = {limit = 3},
  ["esx_drugs:startHarvestCoke"] = {limit = 3},
  ["esx_illegal_drugs:startHarvestCoke"] = {limit = 3},
  ["esx_drugs:startHarvestMeth"] = {limit = 3},
  ["esx_illegal_drugs:startHarvestMeth"] = {limit = 3},
  ["esx_drugs:startHarvestOpium"] = {limit = 3},
  ["esx_illegal_drugs:startHarvestOpium"] = {limit = 3},
  ["esx_blanchisseur:startWhitening"] = {limit = 3},
  ["esx_blanchisseur:washMoney"] = {limit = 3},
  ["esx_blackmoney:washMoney"] = {limit = 3},
  ["esx_moneywash:withdraw"] = {limit = 3},
  ["laundry:washcash"] = {limit = 3},
  ["esx_blanchisseur:washMoney"] = {limit = 3},
  ["esx_handcuffs:cuffing"] = {limit = 5},
  ["gcPhone:_internalAddMessage"] = {limit = 3},
  ["gcPhone:tchat_channel"] = {limit = 3},
  ["js:jailuser"] = {limit = 2},
  ["ljail:jailplayer"] = {limit = 2},
  ["esx_jail:sendToJail"] = {limit = 2},
  ["esx_jailer:sendToJail"] = {limit = 2},
  ["esx-qalle-jail:jailPlayer"] = {limit = 2},
  ["esx_fueldelivery:pay"] = {limit = 2},
  ["esx_carthief:pay"] = {limit = 2},
  ["esx_godirtyjob:pay"] = {limit = 2},
  ["esx_pizza:pay"] = {limit = 2},
  ["esx_ranger:pay"] = {limit = 2},
  ["esx_garbagejob:pay"] = {limit = 2},
  ["esx_slotmachine:sv:2"] = {limit = 2},
  ["esx_dmvschool:pay"] = {limit = 2},
  ["esx_truckerjob:pay"] = {limit = 2},
  ["esx_gopostaljob:pay"] = {limit = 2},
  ["esx_tankerjob:pay"] = {limit = 2},
  ["esx_society:billing"] = {limit = 2},
  ["esx_policejob:message"] = {limit = 4},
}
APIANTICHEATcs.StringsRateLimitEventChecker = { --example someone can send someone to jail with reason: You got fucked ... and then he will get banned!
  "Mod Menu",
  "You got fucked",
  "ATG",
  "anticheat",
  "cheat",
  "Fuck This",
  "discord.gg",
  "Lynx",
  "Huge",
  "Brutan",
  "lynxmenu",
  "API-AC",
  "https://",
  "http://",
  "EULEN",
  "hammafia",
  "onion",
  "executor",
  "desudo",
  "unex"
}
--//BlacklistedNames System\\--
APIANTICHEATcs.BlacklistedNames = true 
APIANTICHEATcs.BlacklistedNamesList = {
    "administrator", "admin", "adm1n", "adm!n", "admln", "moderator", "owner", "nigger", "n1gger", "moderator", "eulencheats", "lynxmenu", "atgmenu", "hacker", "bastard", "hamhaxia", "333gang", "ukrp", "eguk", "n1gger", "n1ga", "nigga", "n1gga", "nigg3r",
    "nig3r", "shagged", "4dm1n", "4dmin", "m0d3r4t0r", "n199er", "n1993r", "rustchance.com", "rustchance", "hellcase.com", "hellcase", "youtube.com", "youtu.be", "youtube", "twitch.tv", "twitch", "anticheat.gg", "anticheat", "fucking", "ψ", "@", "&", "{", "}", ";", "ϟ", "♕", "Æ", "Œ", "‰", "™", "š", "œ", "Ÿ", "µ", "ß",
    "±", "¦", "»", "«", "¼", "½", "¾", "¬", "¿", "Ñ", "®", "©", "²", "·", "•", "°", "þ", "ベ", "ル", "ろ", "ぬ", "ふ", "う", "え", "お", "や", "ゆ", "よ", "わ", "ほ", "へ", "た", "て", "い", "す", "か", "ん", "な", "に", "ら", "ぜ", "む",
    "ち", "と", "し", "は", "き", "く", "ま", "の", "り", "れ", "け", "む", "つ", "さ", "そ", "ひ", "こ", "み", "も", "ね", "る", "め", "ロ", "ヌ", "フ", "ア", "ウ", "エ", "オ", "ヤ", "ユ", "ヨ", "ワ", "ホ", "ヘ", "タ", "テ", "イ", "ス", "カ", "ン",
    "ナ", "ニ", "ラ", "セ", "ム", "チ", "ト", "シ", "ハ", "キ", "ク", "マ", "ノ", "リ", "レ", "ケ", "ム", "ツ", "サ", "ソ", "ヒ", "コ", "ミ", "モ", "ネ", "ル", "メ", "✪", "Ä", "ƒ", "Ã", "¢", "?", "†", "€", "웃", "и", "】", "【", "j4p.pl", "ֆ", "ȶ",
    "你", "好", "爱", "幸", "福", "猫", "狗", "微", "笑", "中", "安", "東", "尼", "杰", "诶", "西", "开", "陈", "瑞", "华", "馬", "塞", "洛", "ダ", "仇", "觉", "感", "衣", "德", "曼", "L͙", "a͙", "l͙", "ľ̶̚͝", "Ḩ̷̤͚̤͑͂̎̎͆", "a̸̢͉̠͎͒͌͐̑̇", "♚", "я", "Ʒ", "Ӂ̴", "Ƹ̴", "≋",
    "API-AC", "civilgamers.com", "civilgamers", "csgoempire.com", "csgoempire", "g4skins.com", "g4skins", "gameodds.gg", "duckfuck.com", "crysishosting.com", "crysishosting", "key-drop.com", "key-drop.pl", "skinhub.com", "skinhub", "`", "¤", "¡",
    "casedrop.eu", "casedrop", "cs.money", "rustypot.com", "ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â", "✈", "⛧", "☭", "☣", "✠", "dkb.xss.ht", "( . )( . )", "⚆", "╮", "╭", "rampage.lt", "?", "xcasecsgo.com", "xcasecsgo", "csgocases.com",
    "csgocases", "K9GrillzUK.co.uk", "moat.gg", "princevidz.com", "princevidz", "pvpro.com", "Pvpro", "ez.krimes.ro", "loot.farm", "arma3fisherslife.net", "arma3fisherslife", "egamers.io", "ifn.gg", "key-drop", "sups.gg", "tradeit.gg",
    "§", "csgotraders.net", "csgotraders", "Σ", "Ξ", "hurtfun.com", "hurtfun", "gamekit.com", "¥", "t.tv", "yandex.ru", "yandex", "csgofly.com", "csgofly", "pornhub.com", "pornhub", "一", "", "Ｊ", "◢", "◤", "⋡", "℟", "ᴮ", "ᴼ", "ᴛᴇᴀᴍ",
    "cs.deals","twat", "STRESS.PW", "<script"
}
--//BlackListed triggers\\-- 
APIANTICHEATcs.FakeTriggers = true --Kick the player that tried to execute or call a blacklisted trigger
APIANTICHEATcs.Triggers = { -- add more :) 
    'HCheat:TempDisableDetection',
	'BsCuff:Cuff696999',
	'adminmenu:allowall',
	'antilynx8r4a:anticheat',
    'antilynxr4:detect',
    'ynx8:anticheat',
	'lynx8:anticheat',
	'hentailover:xdlol',
    'antilynx8:anticheat',
    'antilynxr6:detection',
    'FAC:EzExec',
    'h:xd',
    'redst0nia:checking',
    'esx_policejob:message',
    'esx_lcnjob:handcuff',
    'esx_billing:sendBill',
    'bens_cuff_item:cuff'
}
--//BlacklistedEntities\\--
APIANTICHEATcs.EntityDetect = true
APIANTICHEATcs.EntityDetectBan = true --if someone resp something from list instant ban | if false then if someone resp it will just delete.
APIANTICHEATcs.BlacklistedEntities = { -- Vehicles,Models,Objects,Niggers
	[GetHashKey("cargoplane")] = true,
	[GetHashKey("prop_fnclink_05crnr1")] = true,
	[GetHashKey("xs_prop_hamburgher_wl")] = true,
	[GetHashKey("xs_prop_plastic_bottle_wl")] = true,
	[GetHashKey("prop_windmill_01")] = true,
	[GetHashKey("p_spinning_anus_s")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
	[GetHashKey("stt_prop_ramp_adj_hloop")] = true,
	[GetHashKey("stt_prop_ramp_adj_loop")] = true,
	[GetHashKey("stt_prop_ramp_jump_l")] = true,
	[GetHashKey("stt_prop_ramp_jump_m")] = true,
	[GetHashKey("stt_prop_ramp_jump_s")] = true,
	[GetHashKey("stt_prop_ramp_jump_xl")] = true,
	[GetHashKey("stt_prop_ramp_jump_xs")] = true,
	[GetHashKey("stt_prop_ramp_jump_xxl")] = true,
	[GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
	[GetHashKey("stt_prop_ramp_spiral_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_rock_1_a")] = true,
    [GetHashKey("prop_rock_1_b")] = true,
    [GetHashKey("prop_rock_1_c")] = true,
    [GetHashKey("prop_rock_1_d")] = true,
    [GetHashKey("prop_player_gasmask")] = true,
    [GetHashKey("prop_rock_1_e")] = true,
    [GetHashKey("prop_rock_1_f")] = true,
    [GetHashKey("prop_rock_1_g")] = true,
    [GetHashKey("prop_rock_1_h")] = true,
    [GetHashKey("prop_test_boulder_01")] = true,
    [GetHashKey("prop_test_boulder_02")] = true,
    [GetHashKey("prop_test_boulder_03")] = true,
    [GetHashKey("prop_test_boulder_04")] = true,
    [GetHashKey("apa_mp_apa_crashed_usaf_01a")] = true,
    [GetHashKey("ex_prop_exec_crashdp")] = true,
    [GetHashKey("apa_mp_apa_yacht_o1_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o1_rail_b")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_01")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_03")] = true,
    [GetHashKey("apa_mp_h_yacht_armchair_04")] = true,
    [GetHashKey("apa_mp_h_yacht_barstool_01")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_01")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_02")] = true,
    [GetHashKey("apa_mp_h_yacht_coffee_table_01")] = true,
    [GetHashKey("apa_mp_h_yacht_coffee_table_02")] = true,
    [GetHashKey("apa_mp_h_yacht_floor_lamp_01")] = true,
    [GetHashKey("apa_mp_h_yacht_side_table_01")] = true,
    [GetHashKey("apa_mp_h_yacht_side_table_02")] = true,
    [GetHashKey("apa_mp_h_yacht_sofa_01")] = true,
    [GetHashKey("apa_mp_h_yacht_sofa_02")] = true,
    [GetHashKey("apa_mp_h_yacht_stool_01")] = true,
    [GetHashKey("apa_mp_h_yacht_strip_chair_01")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_01")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_02")] = true,
    [GetHashKey("apa_mp_h_yacht_table_lamp_03")] = true,
    [GetHashKey("prop_flag_columbia")] = true,
    [GetHashKey("apa_mp_apa_yacht_o2_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o2_rail_b")] = true,
    [GetHashKey("apa_mp_apa_yacht_o3_rail_a")] = true,
    [GetHashKey("apa_mp_apa_yacht_o3_rail_b")] = true,
    [GetHashKey("apa_mp_apa_yacht_option1")] = true,
    [GetHashKey("proc_searock_01")] = true,
    [GetHashKey("apa_mp_h_yacht_")] = true,
    [GetHashKey("apa_mp_apa_yacht_option1_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option2_colb")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cola")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_colb")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_colc")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cold")] = true,
    [GetHashKey("apa_mp_apa_yacht_option3_cole")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_cam")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple003")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple1")] = true,
    [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple2")] = true,
    [GetHashKey("apa_mp_apa_yacht_radar_01a")] = true,
    [GetHashKey("apa_mp_apa_yacht_win")] = true,
    [GetHashKey("prop_crashed_heli")] = true,
    [GetHashKey("apa_mp_apa_yacht_door")] = true,
    [GetHashKey("prop_shamal_crash")] = true,
    [GetHashKey("xm_prop_x17_shamal_crash")] = true,
    [GetHashKey("apa_mp_apa_yacht_door2")] = true,
    [GetHashKey("apa_mp_apa_yacht")] = true,
    [GetHashKey("prop_flagpole_2b")] = true,
    [GetHashKey("prop_flagpole_2c")] = true,
    [GetHashKey("prop_flag_canada")] = true,
    [GetHashKey("apa_prop_yacht_float_1a")] = true,
    [GetHashKey("apa_prop_yacht_float_1b")] = true,
    [GetHashKey("apa_prop_yacht_glass_01")] = true,
    [GetHashKey("apa_prop_yacht_glass_02")] = true,
    [GetHashKey("apa_prop_yacht_glass_03")] = true,
    [GetHashKey("apa_prop_yacht_glass_04")] = true,
    [GetHashKey("apa_prop_yacht_glass_05")] = true,
    [GetHashKey("apa_prop_yacht_glass_06")] = true,
    [GetHashKey("apa_prop_yacht_glass_07")] = true,
    [GetHashKey("apa_prop_yacht_glass_08")] = true,
    [GetHashKey("apa_prop_yacht_glass_09")] = true,
    [GetHashKey("apa_prop_yacht_glass_10")] = true,
    [GetHashKey("prop_flag_canada_s")] = true,
    [GetHashKey("prop_flag_eu")] = true,
    [GetHashKey("prop_flag_eu_s")] = true,
    [GetHashKey("prop_target_blue_arrow")] = true,
    [GetHashKey("prop_target_orange_arrow")] = true,
    [GetHashKey("prop_target_purp_arrow")] = true,
    [GetHashKey("prop_target_red_arrow")] = true,
    [GetHashKey("apa_prop_flag_argentina")] = true,
    [GetHashKey("apa_prop_flag_australia")] = true,
    [GetHashKey("apa_prop_flag_austria")] = true,
    [GetHashKey("apa_prop_flag_belgium")] = true,
    [GetHashKey("apa_prop_flag_brazil")] = true,
    [GetHashKey("apa_prop_flag_canadat_yt")] = true,
    [GetHashKey("apa_prop_flag_china")] = true,
    [GetHashKey("apa_prop_flag_columbia")] = true,
    [GetHashKey("apa_prop_flag_croatia")] = true,
    [GetHashKey("apa_prop_flag_czechrep")] = true,
    [GetHashKey("apa_prop_flag_denmark")] = true,
    [GetHashKey("apa_prop_flag_england")] = true,
    [GetHashKey("apa_prop_flag_eu_yt")] = true,
    [GetHashKey("apa_prop_flag_finland")] = true,
    [GetHashKey("apa_prop_flag_france")] = true,
    [GetHashKey("apa_prop_flag_german_yt")] = true,
    [GetHashKey("apa_prop_flag_hungary")] = true,
    [GetHashKey("apa_prop_flag_ireland")] = true,
    [GetHashKey("apa_prop_flag_israel")] = true,
    [GetHashKey("apa_prop_flag_italy")] = true,
    [GetHashKey("apa_prop_flag_jamaica")] = true,
    [GetHashKey("apa_prop_flag_japan_yt")] = true,
    [GetHashKey("apa_prop_flag_canada_yt")] = true,
    [GetHashKey("apa_prop_flag_lstein")] = true,
    [GetHashKey("apa_prop_flag_malta")] = true,
    [GetHashKey("apa_prop_flag_mexico_yt")] = true,
    [GetHashKey("apa_prop_flag_netherlands")] = true,
    [GetHashKey("apa_prop_flag_newzealand")] = true,
    [GetHashKey("apa_prop_flag_nigeria")] = true,
    [GetHashKey("apa_prop_flag_norway")] = true,
    [GetHashKey("apa_prop_flag_palestine")] = true,
    [GetHashKey("apa_prop_flag_poland")] = true,
    [GetHashKey("apa_prop_flag_portugal")] = true,
    [GetHashKey("apa_prop_flag_puertorico")] = true,
    [GetHashKey("apa_prop_flag_russia_yt")] = true,
    [GetHashKey("apa_prop_flag_scotland_yt")] = true,
    [GetHashKey("apa_prop_flag_script")] = true,
    [GetHashKey("apa_prop_flag_slovakia")] = true,
    [GetHashKey("apa_prop_flag_slovenia")] = true,
    [GetHashKey("apa_prop_flag_southafrica")] = true,
    [GetHashKey("apa_prop_flag_southkorea")] = true,
    [GetHashKey("apa_prop_flag_spain")] = true,
    [GetHashKey("apa_prop_flag_sweden")] = true,
    [GetHashKey("apa_prop_flag_switzerland")] = true,
    [GetHashKey("apa_prop_flag_turkey")] = true,
    [GetHashKey("apa_prop_flag_uk_yt")] = true,
    [GetHashKey("apa_prop_flag_us_yt")] = true,
    [GetHashKey("apa_prop_flag_wales")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("prop_flag_france")] = true,
    [GetHashKey("prop_flag_france_s")] = true,
    [GetHashKey("prop_flag_german")] = true,
    [GetHashKey("prop_flag_german_s")] = true,
    [GetHashKey("prop_flag_ireland")] = true,
    [GetHashKey("prop_flag_ireland_s")] = true,
    [GetHashKey("prop_flag_japan")] = true,
    [GetHashKey("prop_flag_japan_s")] = true,
    [GetHashKey("prop_flag_ls")] = true,
    [GetHashKey("prop_flag_lsfd")] = true,
    [GetHashKey("prop_flag_lsfd_s")] = true,
    [GetHashKey("prop_flag_lsservices")] = true,
    [GetHashKey("prop_flag_lsservices_s")] = true,
    [GetHashKey("prop_flag_ls_s")] = true,
    [GetHashKey("prop_flag_mexico")] = true,
    [GetHashKey("prop_flag_mexico_s")] = true,
    [GetHashKey("prop_flag_russia")] = true,
    [GetHashKey("prop_flag_russia_s")] = true,
    [GetHashKey("prop_flag_s")] = true,
    [GetHashKey("prop_flag_sa")] = true,
    [GetHashKey("prop_flag_sapd")] = true,
    [GetHashKey("prop_flag_sapd_s")] = true,
    [GetHashKey("prop_flag_sa_s")] = true,
    [GetHashKey("prop_flag_scotland")] = true,
    [GetHashKey("prop_flag_scotland_s")] = true,
    [GetHashKey("prop_flag_sheriff")] = true,
    [GetHashKey("prop_flag_sheriff_s")] = true,
    [GetHashKey("prop_flag_uk")] = true,
    [GetHashKey("prop_flag_uk_s")] = true,
    [GetHashKey("prop_flag_us")] = true,
    [GetHashKey("prop_flag_usboat")] = true,
    [GetHashKey("prop_flag_us_r")] = true,
    [GetHashKey("prop_flag_us_s")] = true,
    [GetHashKey("prop_aircon_l_03")] = true,
    [GetHashKey("csx_coastsmalrock_05_")] = true,
    [GetHashKey("mp_player_int_rock")] = true,
    [GetHashKey("mp_player_introck")] = true,
    [GetHashKey("prop_flagpole_1a")] = true,
    [GetHashKey("prop_flagpole_2a")] = true,
    [GetHashKey("prop_flagpole_3a")] = true,
    [GetHashKey("prop_a4_pile_01")] = true,
    [GetHashKey("cs2_10_sea_rocks_lod")] = true,
    [GetHashKey("cs2_11_sea_marina_xr_rocks_03_lod")] = true,
    [GetHashKey("prop_gold_cont_01")] = true,
    [GetHashKey("prop_hydro_platform")] = true,
    [GetHashKey("ch3_04_viewplatform_slod")] = true,
    [GetHashKey("ch2_03c_rnchstones_lod")] = true,
    [GetHashKey("proc_mntn_stone01")] = true,
    [GetHashKey("prop_beachflag_le")] = true,
    [GetHashKey("proc_mntn_stone02")] = true,
    [GetHashKey("cs2_10_sea_shipwreck_lod")] = true,
    [GetHashKey("des_shipsink_02")] = true,
    [GetHashKey("prop_flag_japan_s")] = true,
    [GetHashKey("prop_flag_ls")] = true,
    [GetHashKey("prop_flag_lsfd")] = true,
    [GetHashKey("prop_flag_lsfd_s")] = true,
    [GetHashKey("prop_cable_hook_01")] = true,
    [GetHashKey("prop_flag_lsservices")] = true,
    [GetHashKey("prop_flag_lsservices_s")] = true,
    [GetHashKey("prop_flag_ls_s")] = true,
    [GetHashKey("prop_flag_mexico")] = true,
    [GetHashKey("prop_flag_mexico_s")] = true,
    [GetHashKey("csx_coastboulder_00")] = true,
    [GetHashKey("des_tankercrash_01")] = true,
    [GetHashKey("des_tankerexplosion_01")] = true,
    [GetHashKey("des_tankerexplosion_02")] = true,
    [GetHashKey("des_trailerparka_02")] = true,
    [GetHashKey("des_trailerparkb_02")] = true,
    [GetHashKey("prop_gold_vault_fence_l")] = true,
    [GetHashKey("prop_gold_vault_fence_r")] = true,
    [GetHashKey("prop_gold_vault_gate_01")] = true,
    [GetHashKey("prop_bank_vaultdoor")] = true,
    [GetHashKey("des_traincrash_root7")] = true,
    [GetHashKey("prop_flag_russia")] = true,
    [GetHashKey("prop_flag_russia_s")] = true,
    [GetHashKey("prop_flag_s")] = true,
    [GetHashKey("ch2_03c_props_rrlwindmill_lod")] = true,
    [GetHashKey("prop_flag_sa")] = true,
    [GetHashKey("prop_flag_sapd")] = true,
    [GetHashKey("prop_flag_sapd_s")] = true,
    [GetHashKey("prop_flag_sa_s")] = true,
    [GetHashKey("prop_flag_scotland")] = true,
    [GetHashKey("prop_flamingo")] = true,
    [GetHashKey("prop_asteroid_01")] = true,
    [GetHashKey("stt_prop_stunt_bowling_ball")] = true,
    [GetHashKey("stt_prop_stunt_bowling_pin")] = true,
    [GetHashKey("stt_prop_stunt_soccer_ball")] = true,
    [GetHashKey("stt_prop_stunt_soccer_lball")] = true,
    [GetHashKey("stt_prop_stunt_soccer_sball")] = true,
    [GetHashKey("stt_prop_stunt_tube_fn_01")] = true,
    [GetHashKey("stt_prop_stunt_tube_fn_02")] = true,
    [GetHashKey("stt_prop_stunt_tube_fn_03")] = true,
    [GetHashKey("stt_prop_stunt_tube_fn_04")] = true,
    [GetHashKey("stt_prop_stunt_tube_fn_05")] = true,
    [GetHashKey("stt_prop_stunt_domino")] = true,
    [GetHashKey("stt_prop_stunt_jump15")] = true,
    [GetHashKey("stt_prop_stunt_jump30")] = true,
    [GetHashKey("stt_prop_stunt_jump45")] = true,
    [GetHashKey("stt_prop_stunt_jump_l")] = true,
    [GetHashKey("stt_prop_stunt_jump_lb")] = true,
    [GetHashKey("stt_prop_stunt_jump_loop")] = true,
    [GetHashKey("stt_prop_stunt_jump_m")] = true,
    [GetHashKey("stt_prop_stunt_jump_mb")] = true,
    [GetHashKey("stt_prop_stunt_jump_s")] = true,
    [GetHashKey("stt_prop_stunt_jump_sb")] = true,
    [GetHashKey("stt_prop_stunt_landing_zone_01")] = true,
    [GetHashKey("stt_prop_stunt_ramp")] = true,
    [GetHashKey("stt_prop_stunt_target")] = true,
    [GetHashKey("stt_prop_stunt_target_small")] = true,
    [GetHashKey("stt_prop_stunt_target")] = true,
    [GetHashKey("stt_prop_stunt_track_bumps")] = true,
    [GetHashKey("stt_prop_stunt_track_cutout")] = true,
    [GetHashKey("stt_prop_stunt_track_dwlink")] = true,
    [GetHashKey("stt_prop_stunt_track_dwlink_02")] = true,
    [GetHashKey("stt_prop_stunt_track_dwsh15")] = true,
    [GetHashKey("stt_prop_stunt_track_dwshort")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_soccer_goal")] = true,
    [GetHashKey("stt_prop_stunt_tube_jmp2")] = true,
    [GetHashKey("stt_prop_track_stop_sign")] = true,
    [GetHashKey("stt_prop_race_gantry_01")] = true,
    [GetHashKey("stt_prop_race_start_line_01")] = true,
    [GetHashKey("stt_prop_race_start_line_01b")] = true,
    [GetHashKey("stt_prop_race_start_line_02")] = true,
    [GetHashKey("stt_prop_race_start_line_02b")] = true,
    [GetHashKey("stt_prop_race_start_line_03")] = true,
    [GetHashKey("stt_prop_race_start_line_03b")] = true,
    [GetHashKey("stt_prop_race_tannoy")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
    [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
    [GetHashKey("stt_prop_ramp_adj_loop")] = true,
    [GetHashKey("stt_prop_ramp_jump_l")] = true,
    [GetHashKey("stt_prop_ramp_jump_m")] = true,
    [GetHashKey("stt_prop_ramp_jump_s")] = true,
    [GetHashKey("stt_prop_ramp_jump_xl")] = true,
    [GetHashKey("stt_prop_ramp_jump_xs")] = true,
    [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
    [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
    [GetHashKey("stt_prop_ramp_spiral_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
    [GetHashKey("p_crahsed_heli_s")] = true,
    [GetHashKey("prop_rock_4_big2")] = true,
    [GetHashKey("prop_beachflag_le")] = true,
    [GetHashKey("xs_prop_hamburgher_wl")] = true,
    [GetHashKey("prop_xmas_tree_int")] = true,
    [GetHashKey("sr_prop_spec_tube_xxs_01a")] = true,
    [GetHashKey("prop_ld_ferris_wheel")] = true,
    [GetHashKey("prop_const_fence02b")] = true,
    [GetHashKey("prop_container_05a")] = true, --test
    [GetHashKey("prop_container_03b")] = true, --test
    [GetHashKey("prop_mp_ramp_03")] = true 
}
--//Explosions\\--
APIANTICHEATcs.DetectExplosions = true -- Automatically detect blacklisted explosions below
APIANTICHEATcs.ExplosionsList = { -- default is good 
    [0] = { name = "Grenade", log = true, ban = true },
    [1] = { name = "GrenadeLauncher", log = true, ban = true },
    [2] = { name = "Molotov", log = true, ban = true },
    [3] = { name = "Rocket", log = true, ban = true },
    [4] = { name = "TankShell", log = true, ban = false},
    [5] = { name = "Hi_Octane", log = false, ban = false },
    [6] = { name = "Car", log = false, ban = false },
    [7] = { name = "Plance", log = false, ban = false },
    [8] = { name = "PetrolPump", log = false, ban = false },
    [9] = { name = "Bike", log = false, ban = false },
    [10] = { name = "Dir_Steam", log = false, ban = false },
    [11] = { name = "Dir_Flame", log = false, ban = false },
    [12] = { name = "Dir_Water_Hydrant", log = false, ban = false },
    [13] = { name = "Dir_Gas_Canister", log = false, ban = false },
    [14] = { name = "Boat", log = false, ban = false },
    [15] = { name = "Ship_Destroy", log = false, ban = false },
    [16] = { name = "Truck", log = false, ban = false },
    [17] = { name = "Bullet", log = true, ban = false },
    [18] = { name = "SmokeGrenadeLauncher", log = true, ban = true },
    [19] = { name = "SmokeGrenade", log = true, ban = true },
    [20] = { name = "BZGAS", log = true, ban = true },
    [21] = { name = "Flare", log = false, ban = false },
    [22] = { name = "Gas_Canister", log = true, ban = false },
    [23] = { name = "Extinguisher", log = true, ban = true },
    [24] = { name = "Programmablear", ban = false },
    [25] = { name = "Train", log = true, ban = true },
    [26] = { name = "Barrel", log = false, ban = false },
    [27] = { name = "PROPANE", log = false, ban = false },
    [28] = { name = "Blimp", log = false, ban = false },
    [29] = { name = "Dir_Flame_Explode", log = false, ban = false },
    [30] = { name = "Tanker", log = false, ban = false },
    [31] = { name = "PlaneRocket", log = true, ban = false },
    [32] = { name = "VehicleBullet", ban = true },
    [33] = { name = "Gas_Tank", log = false, ban = false },
    [34] = { name = "FireWork", log = true, ban = true },
    [35] = { name = "SnowBall", log = true, ban = false },
    [36] = { name = "ProxMine", log = true, ban = true },
    [37] = { name = "Valkyrie_Cannon", log = true, ban = true }
}
